### ISSUE TITLE
Support for holding down buttons

### ISSUE THREAD

**Issue by Masterlodon** [TheVoidBlock/syncac#1]
I like that I can tab out of the game and still have my player keep clicking in the background but I would like a functionality for holding down right click as well since I have a farm that required the player to eat periodically which doesn't work on the current version.

**Comment by TheVoidBlock** [comment]
I added support for holding down use item. It's in the latest release. [Modrinth](https://modrinth.com/mod/syncac/version/latest) [Github](https://github.com/TheVoidBlock/syncac/releases/latest)
